parameters:
#    rezo.bundle.user.example.class: Rezo\Bundle\UserBundle\Example

services:
#    rezo.bundle.user.example:
#        class: %rezo.bundle.user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#        calls:
#            - [setService, [@service_id]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }